### PR TITLE
Header + Footer + Push Notification pages

### PR DESCRIPTION
**Pull request by MLY-lab**

### CODE REVIEW

**Comment by MLY-lab** [comment]
image
I missed seeing the comment, so should i change that now or can be later?

**Comment by lenhatminh451** [comment]
I've fixed all the mentioned issues, including the font size and Header & Footer

**Review by lenhatminh451 — APPROVED** [review]
All changes are behind main branch, and it works properly on UQ Zone, so I think it's acceptable

**Review by Xiaoran720 — COMMENTED** [review]
Thank you for your efforts.

**Pull request merged**
