### PR TITLE
Add initial backend codebase for the website

### PR DESCRIPTION
**Pull request by lenhatminh451**
The website now has:
- The backend sends a simple message to the frontend
- The frontend displays the message received from the backend

Updated new instructions into the README.md file of the web app

### CODE REVIEW

**Comment by MLY-lab** [comment]
nice

**Comment by MLY-lab** [comment]
nice

**Comment by MLY-lab** [comment]
nice

**Review by Kevin-YANG728 — APPROVED** [review]
Well done!

**Pull request merged**
