### PR TITLE
header footer push-notification

### PR DESCRIPTION
**Pull request by MLY-lab**

### CODE REVIEW

**Comment by lenhatminh451** [comment]
Hey Wenxuan, wait, I'm modifying something that why I closed it

**Comment by lenhatminh451** [comment]
I make some modifications, make sure to pull it before continuing your work:
- I removed the account icon and the Time field, because it'll make more work in the backend, we can add it later
- I moved some styles of previous headers & footers to yours

Also, can you make some modifications:
- Align the "Push" button to the center, or the same length as the form
- The zone's names are too big compared with other fields' contents
- I don't know why, but the Login page's style is affected:
CleanShot 2024-09-22 at 19 33 12@2x

**Comment by MLY-lab** [comment]
ok i will check that

**Comment by lenhatminh451** [comment]
Also, one more important change you should make is applying the Header & Footer for all the pages

**Pull request closed without merging**
